# Generated by Django 5.2.16 on 2026-09-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAppPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(choices=[('news', 'スイスニュース'), ('feeding', '子育て（離乳食記録）'), ('vaccination', '子育て（ワクチン記録）'), ('recipes', '料理・レシピ'), ('games', 'ミニゲーム'), ('colorcheck', '色判定')], max_length=30, verbose_name='アプリ')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Portalに表示する')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_app_preferences', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'Portalアプリ設定',
                'verbose_name_plural': 'Portalアプリ設定',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'app_key'), name='unique_portal_app_preference_per_user')],
            },
        ),
    ]
