# Generated by Django 5.2.16 on 2026-10-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalapppreference',
            name='app_key',
            field=models.CharField(choices=[('news', 'スイスニュース'), ('feeding', '子育て（離乳食記録）'), ('vaccination', '子育て（ワクチン記録）'), ('recipes', '料理・レシピ'), ('games', 'ミニゲーム'), ('colorcheck', '色判定'), ('events', 'イベント・日程調整'), ('chat', 'チャット')], max_length=30, verbose_name='アプリ'),
        ),
    ]
