# Generated by Django 5.2.16 on 2026-10-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_portalapppreference_app_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(choices=[('feeding', '離乳食記録'), ('vaccination', 'ワクチン記録'), ('games', 'ミニゲーム'), ('chat', 'チャット'), ('board', '掲示板')], max_length=30, verbose_name='利用希望アプリ')),
                ('status', models.CharField(choices=[('pending', '確認待ち'), ('approved', '承認'), ('declined', '見送り')], default='pending', max_length=20, verbose_name='ステータス')),
                ('requested_path', models.CharField(blank=True, max_length=500, verbose_name='申請元URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'app_key'), name='unique_app_access_request_per_user')],
            },
        ),
    ]
