# Generated by Django 5.2.16 on 2026-08-31 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name_en', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='VaccineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name_en', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_children', to=settings.AUTH_USER_MODEL)),
                ('birth_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_birth_children', to='vaccination.country')),
                ('default_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_resident_children', to='vaccination.country')),
            ],
            options={
                'ordering': ['date_of_birth', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CountryScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=250)),
                ('source_url', models.URLField(blank=True)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedule_versions', to='vaccination.country')),
            ],
            options={
                'ordering': ['country', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='HealthcareProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_providers', to='vaccination.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_healthcare_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_language', models.CharField(default='ja', max_length=20)),
                ('doctor_language', models.CharField(default='en', max_length=20)),
                ('doctor_show_english', models.BooleanField(default=True)),
                ('date_format', models.CharField(choices=[('ymd', '2026/08/31'), ('dmy_dot', '31.08.2026'), ('dmy_text', '31 Aug 2026')], default='ymd', max_length=20)),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vaccination.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CountryScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=200)),
                ('recommended_age_min_days', models.PositiveIntegerField()),
                ('recommended_age_max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('display_age', models.CharField(blank=True, help_text='例: 2か月、9か月、12か月', max_length=100)),
                ('dose_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vaccination.countryscheduleversion')),
                ('required_components', models.ManyToManyField(related_name='country_schedule_items', to='vaccination.vaccinecomponent')),
            ],
            options={
                'ordering': ['recommended_age_min_days', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VaccineComponentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vaccination.vaccinecomponent')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('components', models.ManyToManyField(related_name='preparations', to='vaccination.vaccinecomponent')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='VaccinePreparationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vaccination.vaccinepreparation')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vaccination.vaccinepreparation')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('preparation_dose_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_reaction', models.BooleanField(default=False)),
                ('reaction_codes', models.JSONField(blank=True, default=list)),
                ('reaction_other', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='vaccination.child')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='vaccination.country')),
                ('healthcare_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='vaccination.healthcareprovider')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_records', to='vaccination.vaccinepreparation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='vaccination.vaccineproduct')),
            ],
            options={
                'ordering': ['-vaccination_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CountryScheduleItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vaccination.countryscheduleitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule_item', 'language_code'), name='unique_country_schedule_item_translation')],
            },
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vaccination.country')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'language_code'), name='unique_country_translation')],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecordComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_components', to='vaccination.vaccinationrecord')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_record_components', to='vaccination.vaccinecomponent')),
            ],
            options={
                'ordering': ['component__name_en'],
                'constraints': [models.UniqueConstraint(fields=('record', 'component'), name='unique_vaccination_record_component')],
            },
        ),
        migrations.AddConstraint(
            model_name='countryscheduleitem',
            constraint=models.UniqueConstraint(fields=('schedule', 'code'), name='unique_country_schedule_item'),
        ),
        migrations.AddConstraint(
            model_name='vaccinecomponenttranslation',
            constraint=models.UniqueConstraint(fields=('component', 'language_code'), name='unique_vaccine_component_translation'),
        ),
        migrations.AddConstraint(
            model_name='vaccinepreparationtranslation',
            constraint=models.UniqueConstraint(fields=('preparation', 'language_code'), name='unique_vaccine_preparation_translation'),
        ),
    ]
