# Generated by Django 5.2.16 on 2026-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryscheduleitem',
            name='recommended_interval_max_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countryscheduleitem',
            name='recommended_interval_min_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
