# Generated by Django 5.2.16 on 2026-08-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_countryscheduleitem_recommended_interval_max_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryscheduleitem',
            name='recommended_interval_from_dose_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
