# Generated by Django 5.2.16 on 2026-08-31 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_countryscheduleitem_recommended_interval_from_dose_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryscheduleitem',
            name='applies_to_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_schedule_items', to='vaccination.vaccineproduct'),
        ),
    ]
