# Generated by Django 5.2.16 on 2026-08-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_countryscheduleitem_applies_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationsettings',
            name='active_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vaccination_settings', to='vaccination.child'),
        ),
    ]
