# Generated by Django 5.2.16 on 2026-08-31 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_vaccinationsettings_active_child'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('edit', 'Can edit'), ('view', 'View only')], default='edit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='vaccination.child')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child', 'user'), name='unique_child_collaborator')],
            },
        ),
    ]
