# Generated by Django 5.2.16 on 2026-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_childcollaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
