# Generated by Django 5.2.16 on 2026-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0007_child_name_en_alter_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationsettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20),
        ),
    ]
