# Generated by Django 5.2.16 on 2026-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='original_language',
            field=models.CharField(choices=[('ja', '日本語'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('en', 'English'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('en', 'English'), ('multi', 'Multilingual')], default='de', max_length=10),
        ),
    ]
