# Generated by Django 5.2.16 on 2026-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_original_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
