# Generated by Django 5.2.16 on 2026-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_ai_error_article_ai_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_date', models.DateField()),
                ('period', models.CharField(choices=[('morning', '朝'), ('afternoon', '午後')], max_length=20)),
                ('summary_ja', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('source_from', models.DateTimeField()),
                ('source_to', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('digest_date', 'period'), name='unique_news_digest_period')],
            },
        ),
    ]
