# Generated by Django 5.2.16 on 2026-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsdigest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdigest',
            name='period',
            field=models.CharField(choices=[('morning', '朝のまとめ'), ('late_morning', '午前のまとめ'), ('afternoon', '午後のまとめ'), ('evening', '夜のまとめ')], max_length=20),
        ),
    ]
