# Generated by Django 5.2.16 on 2026-09-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPushBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_key', models.CharField(max_length=150, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ニュースPush送信履歴',
                'verbose_name_plural': 'ニュースPush送信履歴',
            },
        ),
    ]
