# Generated by Django 5.2.16 on 2026-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspushbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('is_read', models.BooleanField(default=False, verbose_name='確認済み')),
            ],
            options={
                'verbose_name': 'Swiss News コメント',
                'verbose_name_plural': 'Swiss News コメント',
                'ordering': ['-created_at'],
            },
        ),
    ]
