# Generated by Django 5.2.16 on 2026-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_region_article_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspreference',
            name='hidden_regions',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_users', to='news.region'),
        ),
        migrations.AddField(
            model_name='newspreference',
            name='hidden_sources',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_users', to='news.newssource'),
        ),
    ]
