# Generated by Django 5.2.16 on 2026-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newspreference_hidden_regions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank', '銀行口座で応援'), ('other', 'その他の方法で応援')], max_length=20)),
                ('bank_country', models.CharField(blank=True, choices=[('ch', 'スイスの銀行口座'), ('jp', '日本の銀行口座')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Swiss News 応援問い合わせ',
                'verbose_name_plural': 'Swiss News 応援問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
    ]
