# Generated by Django 5.2.16 on 2026-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspreference',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='ダークモード'),
        ),
    ]
