# Generated by Django 5.2.16 on 2026-09-20 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(choices=[('portal', 'Portal'), ('news', 'スイスニュース'), ('feeding', '子育て（離乳食記録）'), ('vaccination', '子育て（ワクチン記録）'), ('recipes', '料理・レシピ'), ('games', 'ミニゲーム'), ('colorcheck', '色判定')], max_length=30, verbose_name='アプリ')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='アクセス日時')),
                ('is_visit_start', models.BooleanField(default=False, verbose_name='新しい訪問')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '利用履歴',
                'verbose_name_plural': '利用履歴',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['app_key', 'accessed_at'], name='usage_analy_app_key_cfe889_idx'), models.Index(fields=['user', 'accessed_at'], name='usage_analy_user_id_eb37c2_idx')],
            },
        ),
    ]
