# Generated by Django 5.2.16 on 2026-09-20 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.UUIDField(verbose_name='タブID')),
                ('app_key', models.CharField(choices=[('portal', 'Portal'), ('news', 'スイスニュース'), ('feeding', '子育て（離乳食記録）'), ('vaccination', '子育て（ワクチン記録）'), ('recipes', '料理・レシピ'), ('games', 'ミニゲーム'), ('colorcheck', '色判定')], max_length=30, verbose_name='利用中のアプリ')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='最終生存確認')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_presences', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'オンライン状態',
                'verbose_name_plural': 'オンライン状態',
                'indexes': [models.Index(fields=['user', 'last_seen'], name='usage_analy_user_id_ca96ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tab_id'), name='unique_online_presence_per_tab')],
            },
        ),
    ]
