# Generated by Django 5.2.16 on 2026-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_analytics', '0002_onlinepresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, verbose_name='匿名訪問者ID')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='閲覧ページ')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='アクセス日時')),
                ('is_visit_start', models.BooleanField(default=False, verbose_name='新しい訪問')),
            ],
            options={
                'verbose_name': '公開ニュース利用履歴',
                'verbose_name_plural': '公開ニュース利用履歴',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['visitor_id', 'accessed_at'], name='usage_analy_visitor_774008_idx')],
            },
        ),
    ]
