# Generated by Django 5.2.16 on 2026-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_analytics', '0003_publicnewsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNewsArticleClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, verbose_name='匿名訪問者ID')),
                ('article_id', models.PositiveBigIntegerField(db_index=True, verbose_name='記事ID')),
                ('article_title', models.CharField(max_length=500, verbose_name='記事タイトル')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='ニュースソース')),
                ('destination_url', models.URLField(max_length=2000, verbose_name='リンク先')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='クリック日時')),
            ],
            options={
                'verbose_name': '公開ニュース記事クリック',
                'verbose_name_plural': '公開ニュース記事クリック',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['visitor_id', 'clicked_at'], name='usage_analy_visitor_dddcc1_idx'), models.Index(fields=['article_id', 'clicked_at'], name='usage_analy_article_9792aa_idx')],
            },
        ),
    ]
