# Generated by Django 5.2.16 on 2026-09-27 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_analytics', '0004_publicnewsarticleclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsArticleClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.PositiveBigIntegerField(db_index=True, verbose_name='記事ID')),
                ('article_title', models.CharField(max_length=500, verbose_name='記事タイトル')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='ニュースソース')),
                ('destination_url', models.URLField(max_length=2000, verbose_name='リンク先')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='クリック日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_article_clicks', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ログインユーザー News記事クリック',
                'verbose_name_plural': 'ログインユーザー News記事クリック',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['user', 'clicked_at'], name='usage_analy_user_id_129b4f_idx'), models.Index(fields=['article_id', 'clicked_at'], name='usage_analy_article_bee4da_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='閲覧ページ')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='アクセス日時')),
                ('is_visit_start', models.BooleanField(default=False, verbose_name='新しい訪問')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_page_events', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ログインユーザー News利用履歴',
                'verbose_name_plural': 'ログインユーザー News利用履歴',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'accessed_at'], name='usage_analy_user_id_46521b_idx')],
            },
        ),
    ]
