# Generated by Django 5.2.16 on 2026-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_analytics', '0005_usernewsarticleclick_usernewsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicnewsarticleclick',
            name='origin_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='クリック元ページ'),
        ),
        migrations.AddField(
            model_name='publicnewsarticleclick',
            name='visit_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='訪問ID'),
        ),
        migrations.AddField(
            model_name='publicnewsevent',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='other', max_length=20, verbose_name='デバイス'),
        ),
        migrations.AddField(
            model_name='publicnewsevent',
            name='is_new_visitor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='初回訪問者'),
        ),
        migrations.AddField(
            model_name='publicnewsevent',
            name='referrer_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='流入元ホスト'),
        ),
        migrations.AddField(
            model_name='publicnewsevent',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='UTM campaign'),
        ),
        migrations.AddField(
            model_name='publicnewsevent',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='UTM medium'),
        ),
        migrations.AddField(
            model_name='publicnewsevent',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='UTM source'),
        ),
        migrations.AddField(
            model_name='publicnewsevent',
            name='visit_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='訪問ID'),
        ),
        migrations.AddIndex(
            model_name='publicnewsarticleclick',
            index=models.Index(fields=['visit_id', 'clicked_at'], name='usage_analy_visit_i_bd415c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicnewsevent',
            index=models.Index(fields=['visit_id', 'accessed_at'], name='usage_analy_visit_i_41b378_idx'),
        ),
        migrations.AddIndex(
            model_name='publicnewsevent',
            index=models.Index(fields=['accessed_at', 'is_new_visitor'], name='usage_analy_accesse_3c2142_idx'),
        ),
    ]
