# Generated by Django 6.0.7 on 2026-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('milk', 'ミルク'), ('food', '離乳食'), ('sleep', '睡眠'), ('diaper', 'おむつ'), ('health', '体調'), ('growth', '成長・行動'), ('other', 'その他')], max_length=20, verbose_name='記録の種類')),
                ('recorded_at', models.DateTimeField(verbose_name='記録日時')),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='量')),
                ('unit', models.CharField(blank=True, help_text='例：ml、分、℃', max_length=20, verbose_name='単位')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '赤ちゃん記録',
                'verbose_name_plural': '赤ちゃん記録',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='予定名')),
                ('start_at', models.DateTimeField(verbose_name='開始日時')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='場所')),
                ('note', models.TextField(blank=True, verbose_name='補足')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要な予定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '予定',
                'verbose_name_plural': '予定',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='やること')),
                ('assigned_to', models.CharField(blank=True, max_length=50, verbose_name='担当者')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='期限')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '通常'), ('high', '高')], default='normal', max_length=10, verbose_name='優先度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('note', models.TextField(blank=True, verbose_name='補足')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お願い・ToDo',
                'verbose_name_plural': 'お願い・ToDo',
                'ordering': ['is_completed', 'due_at', '-created_at'],
            },
        ),
    ]
