# Generated by Django 6.0.7 on 2026-07-31 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_babylog_created_by_schedule_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('home', '家にいる'), ('moving', '移動中'), ('shopping', '買い物中'), ('resting', '休憩中'), ('with_baby', '赤ちゃんと一緒'), ('separate', '別行動中'), ('arrived', '目的地に到着'), ('other', 'その他')], default='home', max_length=20, verbose_name='現在の状態')),
                ('location_name', models.CharField(blank=True, help_text='例：実家、西宮北口、ホテル', max_length=100, verbose_name='現在地の名前')),
                ('message', models.CharField(blank=True, max_length=150, verbose_name='ひとこと')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_status', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '家族の状態',
                'verbose_name_plural': '家族の状態',
                'ordering': ['user__username'],
            },
        ),
    ]
