# Generated by Django 6.0.7 on 2026-07-31 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_familystatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fed_at', models.DateTimeField(verbose_name='授乳時刻')),
                ('amount_ml', models.PositiveIntegerField(verbose_name='ミルク量（ml）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milk_logs', to=settings.AUTH_USER_MODEL, verbose_name='記録者')),
            ],
            options={
                'verbose_name': 'ミルク記録',
                'verbose_name_plural': 'ミルク記録',
                'ordering': ['-fed_at'],
            },
        ),
    ]
