# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sleeplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoopLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(verbose_name='うんちの時刻')),
                ('amount', models.CharField(choices=[('large', '多い'), ('normal', 'ふつう'), ('small', '少ない')], default='normal', max_length=10, verbose_name='うんちの量')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_poop_logs', to=settings.AUTH_USER_MODEL, verbose_name='記録者')),
            ],
            options={
                'verbose_name': 'うんち記録',
                'verbose_name_plural': 'うんち記録',
                'ordering': ['-happened_at'],
            },
        ),
    ]
