# Generated by Django 6.0.7 on 2026-07-31 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pooplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('discussed_at', models.DateTimeField(verbose_name='話し合った日時')),
                ('decisions', models.TextField(verbose_name='決定事項')),
                ('next_actions', models.TextField(blank=True, verbose_name='次にやること')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_notes', to=settings.AUTH_USER_MODEL, verbose_name='記録者')),
            ],
            options={
                'verbose_name': '家族会議メモ',
                'verbose_name_plural': '家族会議メモ',
                'ordering': ['-discussed_at'],
            },
        ),
    ]
