# Generated by Django 6.0.7 on 2026-07-31 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_meetingnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
                ('accuracy', models.PositiveIntegerField(blank=True, null=True, verbose_name='精度（m）')),
                ('shared_at', models.DateTimeField(auto_now=True, verbose_name='共有日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_location', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '共有現在地',
                'verbose_name_plural': '共有現在地',
                'ordering': ['-shared_at'],
            },
        ),
    ]

