# Generated by Django 6.0.7 on 2026-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sharedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeplog',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='起床時刻'),
        ),
    ]