# Generated by Django 6.0.7 on 2026-08-01 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='お知らせ内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notices', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '重要なお知らせ',
                'verbose_name_plural': '重要なお知らせ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
