# Generated by Django 6.0.7 on 2026-08-01 10:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_importantnotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='内容')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='合計金額')),
                ('currency', models.CharField(choices=[('JPY', '日本円'), ('CHF', 'スイスフラン'), ('CNY', '中国元'), ('EUR', 'ユーロ')], default='JPY', max_length=3, verbose_name='通貨')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='支払日時')),
                ('category', models.CharField(choices=[('food', '食事'), ('transport', '交通'), ('shopping', '買い物'), ('accommodation', '宿泊'), ('baby', '赤ちゃん'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='支払った人')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='負担額')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.expense', verbose_name='支出')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_shares', to=settings.AUTH_USER_MODEL, verbose_name='負担する人')),
            ],
            options={
                'verbose_name': '支出の負担額',
                'verbose_name_plural': '支出の負担額',
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('expense', 'user'), name='unique_expense_share_user')],
            },
        ),
    ]
