# Generated by Django 6.0.7 on 2026-08-01 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_expense_expenseshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyGrowthNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='記録日')),
                ('content', models.TextField(verbose_name='記録内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_growth_notes', to=settings.AUTH_USER_MODEL, verbose_name='記録者')),
            ],
            options={
                'verbose_name': '赤ちゃんの成長メモ',
                'verbose_name_plural': '赤ちゃんの成長メモ',
                'ordering': ['-observed_on', '-created_at'],
            },
        ),
    ]
