# Generated by Django 5.2.16 on 2026-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_babygrowthnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='person',
            field=models.CharField(choices=[('baby', '赤ちゃん'), ('mama', 'ママ'), ('papa', 'パパ'), ('family', '家族全員'), ('other', 'その他')], default='family', max_length=20, verbose_name='誰の予定'),
        ),
    ]
