# Generated by Django 5.2.16 on 2026-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schedule_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='選択肢に表示する')),
            ],
            options={
                'verbose_name': '家族メンバー',
                'verbose_name_plural': '家族メンバー',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='person',
        ),
        migrations.AddField(
            model_name='schedule',
            name='people',
            field=models.ManyToManyField(related_name='schedules', to='core.familymember', verbose_name='誰の予定'),
        ),
    ]
