# Generated by Django 5.2.16 on 2026-08-07 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_penalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='旅行名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('members', models.ManyToManyField(blank=True, related_name='travel_groups', to=settings.AUTH_USER_MODEL, verbose_name='参加メンバー')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_travel_groups', to=settings.AUTH_USER_MODEL, verbose_name='代表者')),
            ],
            options={
                'verbose_name': '旅行管理アプリ',
                'verbose_name_plural': '旅行管理アプリ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='babygrowthnote',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baby_growth_notes', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='babylog',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baby_logs', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='expense',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='importantnotice',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='important_notices', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='milklog',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milk_logs', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='pooplog',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poop_logs', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AddField(
            model_name='task',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
