# Generated by Django 5.2.16 on 2026-08-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_travelgroup_babygrowthnote_travel_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('travel_group', 'name'), name='unique_family_member_per_travel_group'),
        ),
    ]
