# Generated by Django 5.2.16 on 2026-08-07 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_familymember_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='familymember',
            name='unique_family_member_per_travel_group',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_family_members', to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('travel_group', 'name'), name='unique_family_member_name_per_travel_group'),
        ),
    ]
