# Generated by Django 5.2.16 on 2026-08-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_familymember_unique_family_member_per_travel_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familystatus',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_statuses', to='core.travelgroup', verbose_name='家族旅行'),
        ),
        migrations.AddField(
            model_name='sharedlocation',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_locations', to='core.travelgroup', verbose_name='旅行管理アプリ'),
        ),
        migrations.AlterField(
            model_name='familystatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_statuses', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='sharedlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_locations', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddConstraint(
            model_name='familystatus',
            constraint=models.UniqueConstraint(fields=('travel_group', 'user'), name='unique_family_status_per_travel_user'),
        ),
        migrations.AddConstraint(
            model_name='sharedlocation',
            constraint=models.UniqueConstraint(fields=('travel_group', 'user'), name='unique_shared_location_per_travel_user'),
        ),
    ]
