# Generated by Django 5.2.16 on 2026-08-07 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_familystatus_travel_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_travel_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
