# Generated by Django 5.2.16 on 2026-08-07 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_travelgroup_archived_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='familymember',
            name='unique_family_member_name_per_travel_group',
        ),
        migrations.AddField(
            model_name='familymember',
            name='member_type',
            field=models.CharField(choices=[('adult', '大人'), ('child', '子ども'), ('baby', '赤ちゃん')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.travelgroup'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_family_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('travel_group', 'name'), name='unique_family_member_name_per_travel'),
        ),
    ]
