# Generated by Django 5.2.16 on 2026-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
