# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_travelgroup_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, verbose_name='ニックネーム'),
        ),
    ]
