# Generated by Django 5.2.16 on 2026-09-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_setup_completed',
            field=models.BooleanField(default=False, verbose_name='初回アプリ選択完了'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname_setup_completed',
            field=models.BooleanField(default=False, verbose_name='初回ニックネーム設定完了'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_setup_completed',
            field=models.BooleanField(default=False, verbose_name='初回パスワード変更完了'),
        ),
    ]
