from django.urls import path

from . import views

app_name = "travel"

urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "switch/<int:travel_group_id>/",
        views.switch_travel_group,
        name="switch_travel_group",
    ),
    path(
        "groups/",
        views.travel_group_list,
        name="travel_group_list",
    ),
    path(
        "groups/create/",
        views.travel_group_create,
        name="travel_group_create",
    ),
    path(
        "groups/<int:travel_group_id>/settings/",
        views.travel_group_settings,
        name="travel_group_settings",
    ),
    path(
        "groups/<int:travel_group_id>/members/add/",
        views.travel_group_member_add,
        name="travel_group_member_add",
    ),
    path(
        "groups/<int:travel_group_id>/members/<int:user_id>/remove/",
        views.travel_group_member_remove,
        name="travel_group_member_remove",
    ),
    path(
        "groups/<int:travel_group_id>/family/add/",
        views.family_member_add,
        name="family_member_add",
    ),
    path(
        "groups/<int:travel_group_id>/family/<int:family_member_id>/remove/",
        views.family_member_remove,
        name="family_member_remove",
    ),
    path(
        "groups/<int:travel_group_id>/delete/",
        views.travel_group_delete,
        name="travel_group_delete",
    ),
    path(
        "schedule/",
        views.schedule_list,
        name="schedule_list",
    ),
    path(
        "schedule/add/",
        views.schedule_create,
        name="schedule_create",
    ),
    path(
        "schedule/<int:schedule_id>/edit/",
        views.schedule_update,
        name="schedule_update",
    ),
    path(
        "schedule/<int:schedule_id>/delete/",
        views.schedule_delete,
        name="schedule_delete",
    ),
    path(
        "tasks/",
        views.task_list,
        name="task_list",
    ),
    path(
        "tasks/add/",
        views.task_create,
        name="task_create",
    ),
    path(
        "tasks/<int:task_id>/edit/",
        views.task_update,
        name="task_update",
    ),
    path(
        "tasks/<int:task_id>/delete/",
        views.task_delete,
        name="task_delete",
    ),
    path(
        "tasks/<int:task_id>/toggle/",
        views.task_toggle,
        name="task_toggle",
    ),
    path(
        "baby/add/",
        views.baby_log_create,
        name="baby_log_create",
    ),
    path(
        "family/status/",
        views.family_status_update,
        name="family_status_update",
    ),
    path(
        "baby/milk/add/",
        views.milk_log_create,
        name="milk_log_create",
    ),
    path(
        "baby/milk/quick/<int:amount_ml>/",
        views.milk_log_quick_create,
        name="milk_log_quick_create",
    ),
    path(
        "baby/sleep/add/",
        views.sleep_log_create,
        name="sleep_log_create",
    ),
    path(
        "baby/sleep/start/",
        views.sleep_start,
        name="sleep_start",
    ),
    path(
        "baby/sleep/end/",
        views.sleep_end,
        name="sleep_end",
    ),
    path(
        "baby/poop/add/",
        views.poop_log_create,
        name="poop_log_create",
    ),
    path(
        "meeting/",
        views.meeting_note_list,
        name="meeting_note_list",
    ),
    path(
        "meeting/add/",
        views.meeting_note_create,
        name="meeting_note_create",
    ),
    path(
        "meeting/<int:note_id>/edit/",
        views.meeting_note_update,
        name="meeting_note_update",
    ),
    path(
        "meeting/<int:note_id>/delete/",
        views.meeting_note_delete,
        name="meeting_note_delete",
    ),
    path(
        "family/<int:user_id>/photo/",
        views.profile_photo,
        name="profile_photo",
    ),
    path(
        "location/share/",
        views.share_location,
        name="share_location",
    ),
    path(
        "expenses/add/",
        views.expense_create,
        name="expense_create",
    ),
    path(
        "expenses/",
        views.expense_list,
        name="expense_list",
    ),
    path(
        "expenses/settlement/",
        views.expense_settlement,
        name="expense_settlement",
    ),
    path(
        "expenses/add/",
        views.expense_create,
        name="expense_create",
    ),
    path(
        "expenses/<int:expense_id>/edit/",
        views.expense_update,
        name="expense_update",
    ),
    path(
        "expenses/<int:expense_id>/delete/",
        views.expense_delete,
        name="expense_delete",
    ),
    path(
        "baby/growth-notes/",
        views.baby_growth_note_list,
        name="baby_growth_note_list",
    ),
    path(
        "baby/growth-notes/add/",
        views.baby_growth_note_create,
        name="baby_growth_note_create",
    ),
    path(
        "baby/growth-notes/<int:note_id>/edit/",
        views.baby_growth_note_update,
        name="baby_growth_note_update",
    ),
    path(
        "baby/growth-notes/<int:note_id>/delete/",
        views.baby_growth_note_delete,
        name="baby_growth_note_delete",
    ),
    
]