from django.urls import path

from . import views


app_name = "feeding"

urlpatterns = [
    path(
        "",
        views.today,
        name="today",
    ),
    path(
        "foods/",
        views.food_list,
        name="food_list",
    ),
    path(
        "foods/add/",
        views.food_create,
        name="food_create",
    ),
    path(
        "foods/<int:food_id>/",
        views.food_detail,
        name="food_detail",
    ),
    path(
        "dishes/add/",
        views.dish_create,
        name="dish_create",
    ),
    path(
        "allergens/",
        views.allergen_list,
        name="allergen_list",
    ),
    path(
        "allergens/<int:allergen_id>/",
        views.allergen_detail,
        name="allergen_detail",
    ),
    path(
        "meals/<int:meal_number>/",
        views.meal_edit,
        name="meal_edit",
    ),
    path(
        "meals/<int:meal_number>/delete/",
        views.meal_delete,
        name="meal_delete",
    ),
    path(
        "meal-items/<int:meal_item_id>/reaction/",
        views.allergy_reaction_edit,
        name="allergy_reaction_edit",
    ),
    path(
        "meal-items/<int:meal_item_id>/reaction/delete/",
        views.allergy_reaction_delete,
        name="allergy_reaction_delete",
    ),
    path(
        "reaction-photos/<int:photo_id>/delete/",
        views.allergy_photo_delete,
        name="allergy_photo_delete",
    ),
    path(
        "settings/",
        views.settings_view,
        name="settings",
    ),
    path(
        "babies/add/",
        views.baby_create,
        name="baby_create",
    ),
    path(
        "babies/<int:baby_id>/members/add/",
        views.baby_member_add,
        name="baby_member_add",
    ),
    path(
        (
            "babies/<int:baby_id>/members/"
            "<int:membership_id>/toggle-edit/"
        ),
        views.baby_member_toggle_edit,
        name="baby_member_toggle_edit",
    ),
    path(
        (
            "babies/<int:baby_id>/members/"
            "<int:membership_id>/delete/"
        ),
        views.baby_member_delete,
        name="baby_member_delete",
    ),
    path(
        "babies/<int:baby_id>/select/",
        views.select_baby,
        name="select_baby",
    ),
]