"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.
"""

from pathlib import Path
import os

import dj_database_url
from django.utils.translation import gettext_lazy as _


# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------------------
# Security
# ------------------------------------------------------------------------------

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-key",
)

DEBUG = os.environ.get(
    "DEBUG",
    "True",
).lower() == "true"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# ------------------------------------------------------------------------------
# Applications
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "portal.apps.PortalConfig",
    "travel.apps.TravelConfig",
    "feeding.apps.FeedingConfig",
    "games.apps.GamesConfig",
    "vaccination.apps.VaccinationConfig",
    "colorcheck.apps.ColorCheckConfig",
    "recipes.apps.RecipesConfig",
    "news.apps.NewsConfig",

    # お知らせ
    "board.apps.BoardConfig",

    # チャット
    "chat.apps.ChatConfig",

    # イベント・日程調整
    "event_scheduler.apps.EventSchedulerConfig",

    "usage_analytics.apps.UsageAnalyticsConfig",
]


# ------------------------------------------------------------------------------
# Middleware
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "portal.middleware.PublicUserAccessMiddleware",

    # App usage tracking
    "usage_analytics.middleware.UsageAnalyticsMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


# ------------------------------------------------------------------------------
# Templates
# ------------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django.DjangoTemplates"
        ),
        "DIRS": [
            BASE_DIR / "templates"
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth.context_processors."
                    "auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),

                "portal.context_processors.admin_attention_counts",

                "travel.context_processors.current_travel_group",
                "vaccination.context_processors.vaccination_ui",
                "recipes.context_processors.recipe_ui_settings",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# ------------------------------------------------------------------------------
# Database
# ------------------------------------------------------------------------------

DATABASE_PATH = os.environ.get(
    "DATABASE_PATH",
    str(
        BASE_DIR / "db.sqlite3"
    ),
)

DATABASES = {
    "default": dj_database_url.config(
        default=(
            f"sqlite:///{DATABASE_PATH}"
        ),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# ------------------------------------------------------------------------------
# Password validation
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ------------------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "ja"

LANGUAGES = [
    ("ja", _("日本語")),
    ("en", _("English")),
    ("de", _("Deutsch")),
    ("fr", "Français"),
    ("zh-hans", _("中文")),
]

TIME_ZONE = "Europe/Zurich"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# ------------------------------------------------------------------------------
# Static files
# ------------------------------------------------------------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = (
    BASE_DIR / "staticfiles"
)

STORAGES = {
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# ------------------------------------------------------------------------------
# Default primary key
# ------------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ------------------------------------------------------------------------------
# Login / Logout
# ------------------------------------------------------------------------------

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = (
    "portal:home"
)

LOGOUT_REDIRECT_URL = "login"

# ------------------------------------------------------------------------------
# Authentication
# ------------------------------------------------------------------------------

AUTHENTICATION_BACKENDS = [
    "portal.backends.EmailOrUsernameBackend",
]


# =========================================================
# Swiss News Web Push
# =========================================================

VAPID_PUBLIC_KEY = os.environ.get(
    "VAPID_PUBLIC_KEY",
    "",
)

VAPID_PRIVATE_KEY = os.environ.get(
    "VAPID_PRIVATE_KEY",
    "",
)

VAPID_CONTACT_EMAIL = os.environ.get(
    "VAPID_CONTACT_EMAIL",
    "",
)


# =========================================================
# Swiss News support
# =========================================================

SWISS_NEWS_TWINT_URL = os.getenv(
    "SWISS_NEWS_TWINT_URL",
    "",
)

SWISS_NEWS_BITCOIN_ADDRESS = (
    "bc1qcf3akr70r0rsjkqphsm6aldgqk9r32e9c475xc"
)


# =========================================================
# Email
# =========================================================

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True


EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    "",
)


# RenderでGmail情報が設定されている場合は
# 本物のメールを送信する。
#
# ローカルで環境変数がない場合は
# メール内容をターミナルに表示する。

if (
    EMAIL_HOST_USER
    and EMAIL_HOST_PASSWORD
):

    EMAIL_BACKEND = (
        "django.core.mail.backends."
        "smtp.EmailBackend"
    )

else:

    EMAIL_BACKEND = (
        "django.core.mail.backends."
        "console.EmailBackend"
    )


DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Yapp <yapp.admin@gmail.com>",
)

SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Yapp管理者への通知先

ADMIN_NOTIFICATION_EMAIL = os.getenv(
    "ADMIN_NOTIFICATION_EMAIL",
    "yapp.admin@gmail.com",
)


# 古いコードとの互換性のため残す。
# 今後は基本的に
# ADMIN_NOTIFICATION_EMAIL を使用する。

SWISS_NEWS_SUPPORT_EMAIL = os.getenv(
    "SWISS_NEWS_SUPPORT_EMAIL",
    ADMIN_NOTIFICATION_EMAIL,
)


EMAIL_TIMEOUT = 20