# Generated by Django 5.2.16 on 2026-10-10 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissBoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('body', models.TextField(max_length=500, verbose_name='本文')),
                ('category', models.CharField(choices=[('marketplace', '売買・譲渡・レンタル'), ('housing', '不動産・住まい'), ('jobs', '求人・仕事探し'), ('friends', '仲間募集'), ('events', 'イベント'), ('lessons', 'レッスン・習い事'), ('parenting', '育児・教育'), ('services', 'サービス・ビジネス'), ('recommendations', 'みんなのおすすめ'), ('questions', '質問・雑談')], db_index=True, max_length=30, verbose_name='カテゴリー')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='サブカテゴリー')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='地域')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開'), ('hidden', '非公開')], db_index=True, default='draft', max_length=20, verbose_name='公開状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swiss_board_posts', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'スイス掲示板の投稿',
                'verbose_name_plural': 'スイス掲示板の投稿',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='swiss_board_status_817315_idx')],
            },
        ),
    ]
