# Generated by Django 5.2.16 on 2026-10-10 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiss_board', '0002_swissboardprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissBoardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500, verbose_name='コメント本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swiss_board_comments', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='swiss_board.swissboardpost', verbose_name='投稿')),
            ],
            options={
                'verbose_name': '掲示板コメント',
                'verbose_name_plural': '掲示板コメント',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
