# Generated by Django 5.2.16 on 2026-10-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiss_board', '0003_swissboardcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='swissboardcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='swiss_board.swissboardcomment', verbose_name='返信先コメント'),
        ),
    ]
