# Generated by Django 5.2.16 on 2026-10-10 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiss_board', '0004_swissboardcomment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissBoardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'コメント'), ('reply', '返信')], max_length=20, verbose_name='通知種類')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通知日時')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_board_sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='通知のきっかけとなった人')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='swiss_board.swissboardcomment', verbose_name='対象コメント')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_board_notifications', to=settings.AUTH_USER_MODEL, verbose_name='通知先')),
            ],
            options={
                'verbose_name': '掲示板通知',
                'verbose_name_plural': '掲示板通知',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'comment'), name='sb_unique_recipient_comment_notice')],
            },
        ),
    ]
