# Generated by Django 5.2.16 on 2026-09-02 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(choices=[('hotcook', 'ヘルシオ'), ('chefdrum', 'シェフドラム')], max_length=20, verbose_name='種類')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('model_number', models.CharField(max_length=50, unique=True, verbose_name='型番')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='食材名')),
                ('category', models.CharField(choices=[('meat', '肉'), ('fish', '魚介'), ('vegetable', '野菜'), ('fruit', '果物'), ('egg', '卵'), ('dairy', '乳製品'), ('soy', '豆・大豆製品'), ('grain', '米・麺・穀類'), ('mushroom', 'きのこ'), ('seasoning', '調味料'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリー')),
                ('is_seasoning', models.BooleanField(default=False, verbose_name='調味料')),
                ('switzerland_availability', models.PositiveSmallIntegerField(default=5, help_text='1〜5。5が最も入手しやすい。', verbose_name='スイスでの入手しやすさ')),
            ],
        ),
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='気分')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='栄養')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='料理名')),
                ('category', models.CharField(choices=[('japanese', '和食'), ('western', '洋食'), ('chinese', '中華'), ('korean', '韓国料理'), ('curry', 'カレー'), ('soup', 'スープ'), ('pasta', 'パスタ・麺'), ('rice', 'ご飯もの'), ('side', '副菜'), ('other', 'その他')], default='other', max_length=20, verbose_name='料理カテゴリー')),
                ('cooking_mode', models.CharField(choices=[('auto', '自動調理'), ('manual', '手動調理')], max_length=20, verbose_name='調理方法')),
                ('cooking_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='調理時間（分）')),
                ('servings', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='何人分')),
                ('menu_number', models.CharField(blank=True, help_text='自動メニューの場合。例: 3、1-20など', max_length=50, verbose_name='メニュー番号')),
                ('appliance_operation', models.TextField(help_text='例: メニューを選ぶ → 3番 → スタート / 手動 → 煮物を作る → まぜる → 20分 → スタート', verbose_name='調理家電の操作方法')),
                ('preparation', models.TextField(blank=True, verbose_name='下ごしらえ・作り方')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='出典')),
                ('source_url', models.URLField(blank=True, verbose_name='出典URL')),
                ('is_official', models.BooleanField(default=False, verbose_name='公式レシピ')),
                ('verified_for_model', models.BooleanField(default=False, verbose_name='対象機種で使用可能と確認済み')),
                ('switzerland_score', models.PositiveSmallIntegerField(default=5, help_text='1〜5。5が最も材料を揃えやすい。', verbose_name='スイスでの作りやすさ')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.appliance', verbose_name='調理家電')),
                ('mood_tags', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.moodtag', verbose_name='気分タグ')),
                ('nutrition_tags', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.nutritiontag', verbose_name='栄養タグ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, verbose_name='分量')),
                ('is_optional', models.BooleanField(default=False, verbose_name='なくてもよい')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
        migrations.CreateModel(
            name='RecipePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('favorite', 'お気に入り'), ('dislike', 'あまり好まない')], max_length=20, verbose_name='評価')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_per_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'appliance'), name='unique_recipe_per_appliance'),
        ),
        migrations.AddConstraint(
            model_name='recipepreference',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_preference_per_user'),
        ),
    ]
