# Generated by Django 5.2.16 on 2026-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_seasoning',
            field=models.BooleanField(default=False, help_text='このレシピ内で食材検索の対象外にする場合はON。', verbose_name='調味料として扱う'),
        ),
    ]
