# Generated by Django 5.2.16 on 2026-09-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_is_seasoning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_seasoning',
        ),
    ]
