# Generated by Django 5.2.16 on 2026-09-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredient_is_seasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='search_group',
            field=models.CharField(blank=True, db_index=True, help_text='例：牛薄切り肉→牛肉、鶏もも肉→鶏肉。空欄の場合は食材名と同じ扱い。', max_length=100, verbose_name='食材検索グループ'),
        ),
    ]
