# Generated by Django 5.2.16 on 2026-09-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_search_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_make_ahead',
            field=models.BooleanField(default=False, verbose_name='作りおき向き'),
        ),
    ]
