# Generated by Django 5.2.16 on 2026-09-02 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_drop_legacy_storage_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepreference',
            name='make_ahead_override',
            field=models.BooleanField(blank=True, null=True, verbose_name='作りおき判定の上書き'),
        ),
        migrations.AddField(
            model_name='recipepreference',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='recipepreference',
            name='preference',
            field=models.CharField(blank=True, choices=[('favorite', 'お気に入り'), ('dislike', 'あまり好まない')], default='', max_length=20, verbose_name='好み（旧方式）'),
        ),
        migrations.CreateModel(
            name='RecipeHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_households_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeHouseholdInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('accepted', '参加済み'), ('declined', '辞退')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='recipes.recipehousehold')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeHouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='recipes.recipehousehold')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_household_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], default='medium', max_length=10, verbose_name='文字サイズ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
