# Generated by Django 5.2.16 on 2026-08-02 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='アレルゲン名')),
                ('classification', models.CharField(choices=[('required', '義務表示'), ('recommended', '推奨表示')], max_length=20, verbose_name='区分')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': 'アレルゲン',
                'verbose_name_plural': 'アレルゲン',
                'ordering': ['classification', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '赤ちゃん',
                'verbose_name_plural': '赤ちゃん',
                'ordering': ['birth_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='料理ジャンル名')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': '料理ジャンル',
                'verbose_name_plural': '料理ジャンル',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ジャンル名')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': '食材ジャンル',
                'verbose_name_plural': '食材ジャンル',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='料理名')),
                ('is_user_created', models.BooleanField(default=False, verbose_name='手動追加した料理')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='feeding.dishcategory', verbose_name='料理ジャンル')),
            ],
            options={
                'verbose_name': '料理',
                'verbose_name_plural': '料理',
                'ordering': ['category__display_order', 'category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='食材名')),
                ('is_user_created', models.BooleanField(default=False, verbose_name='手動追加した食材')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('allergens', models.ManyToManyField(blank=True, related_name='foods', to='feeding.allergen', verbose_name='アレルゲン')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='feeding.foodcategory', verbose_name='ジャンル')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'ordering': ['category__display_order', 'category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='表示順')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='feeding.dish', verbose_name='料理')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_ingredients', to='feeding.food', verbose_name='食材')),
            ],
            options={
                'verbose_name': '料理の材料',
                'verbose_name_plural': '料理の材料',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='dishes', through='feeding.DishIngredient', to='feeding.food', verbose_name='含まれる食材'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'food'), name='unique_food_per_dish'),
        ),
    ]
