# Generated by Django 5.2.16 on 2026-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='show_in_first_year_list',
            field=models.BooleanField(default=True, verbose_name='1歳までリストに表示'),
        ),
    ]
