# Generated by Django 5.2.16 on 2026-08-02 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_food_show_in_first_year_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('meal_number', models.PositiveSmallIntegerField(choices=[(1, '1食目'), (2, '2食目'), (3, '3食目')], verbose_name='食事番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='feeding.baby', verbose_name='赤ちゃん')),
            ],
            options={
                'verbose_name': '食事記録',
                'verbose_name_plural': '食事記録',
                'ordering': ['-date', 'meal_number'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('food', '食材'), ('dish', '料理')], max_length=10, verbose_name='種類')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='実際に食べた量')),
                ('unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('tsp', '小さじ'), ('tbsp', '大さじ')], max_length=10, verbose_name='単位')),
                ('reaction', models.CharField(choices=[('love', '大喜び'), ('happy', '嬉'), ('normal', '普'), ('unsure', '微妙')], max_length=10, verbose_name='反応')),
                ('has_allergy_symptoms', models.BooleanField(default=False, verbose_name='症状あり')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='feeding.dish', verbose_name='料理')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='feeding.food', verbose_name='食材')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeding.meal', verbose_name='食事記録')),
            ],
            options={
                'verbose_name': '食事内容',
                'verbose_name_plural': '食事内容',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MealItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_item_ingredient_snapshots', to='feeding.food', verbose_name='食材')),
                ('meal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_snapshots', to='feeding.mealitem', verbose_name='食事内容')),
            ],
            options={
                'verbose_name': '食事時点の料理材料',
                'verbose_name_plural': '食事時点の料理材料',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('baby', 'date', 'meal_number'), name='unique_meal_per_baby_date_number'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dish__isnull', True), ('food__isnull', False), ('item_type', 'food')), models.Q(('dish__isnull', False), ('food__isnull', True), ('item_type', 'dish')), _connector='OR'), name='meal_item_matches_selected_type'),
        ),
        migrations.AddConstraint(
            model_name='mealitemingredient',
            constraint=models.UniqueConstraint(fields=('meal_item', 'food'), name='unique_food_per_meal_item_snapshot'),
        ),
    ]
