# Generated by Django 5.2.16 on 2026-08-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0003_meal_mealitem_mealitemingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_time', models.TimeField(blank=True, null=True, verbose_name='症状が出た時刻')),
                ('minutes_after_eating', models.PositiveIntegerField(blank=True, null=True, verbose_name='食後何分で症状が出たか')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='症状')),
                ('body_locations', models.JSONField(blank=True, default=list, verbose_name='症状が出た場所')),
                ('other_symptom', models.CharField(blank=True, max_length=255, verbose_name='その他の症状')),
                ('other_location', models.CharField(blank=True, max_length=255, verbose_name='その他の場所')),
                ('visited_doctor', models.BooleanField(default=False, verbose_name='受診した')),
                ('medical_institution', models.CharField(blank=True, max_length=200, verbose_name='医療機関名')),
                ('doctor_diagnosis', models.TextField(blank=True, verbose_name='医師の診断')),
                ('doctor_instructions', models.TextField(blank=True, verbose_name='医師からの指示')),
                ('avoidance_instructed', models.BooleanField(default=False, verbose_name='除去を指示された')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('meal_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_reaction', to='feeding.mealitem', verbose_name='食事内容')),
            ],
            options={
                'verbose_name': 'アレルギー症状',
                'verbose_name_plural': 'アレルギー症状',
                'ordering': ['-meal_item__meal__date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllergyReactionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='allergy_reactions/%Y/%m/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='feeding.allergyreaction', verbose_name='アレルギー症状')),
            ],
            options={
                'verbose_name': 'アレルギー症状の写真',
                'verbose_name_plural': 'アレルギー症状の写真',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
