# Generated by Django 5.2.16 on 2026-08-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0004_allergyreaction_allergyreactionphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('grain', '穀類'), ('vegetable_fruit', '野菜・果物'), ('fish', '魚'), ('meat', '肉'), ('tofu', '豆腐'), ('egg', '卵'), ('dairy', '乳製品'), ('other', '比較対象外')], max_length=30, unique=True, verbose_name='コード')),
                ('name', models.CharField(max_length=50, verbose_name='食品群名')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': '標準量用食品群',
                'verbose_name_plural': '標準量用食品群',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='feeding_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='feeding.feedinggroup', verbose_name='標準量用食品群'),
        ),
        migrations.CreateModel(
            name='FeedingGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age_months', models.PositiveSmallIntegerField(verbose_name='開始月齢')),
                ('max_age_months', models.PositiveSmallIntegerField(verbose_name='終了月齢')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最小量')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最大量')),
                ('unit', models.CharField(choices=[('g', 'g'), ('egg', '個')], default='g', max_length=10, verbose_name='単位')),
                ('food_form_note', models.CharField(blank=True, max_length=200, verbose_name='食品形態・補足')),
                ('display_note', models.CharField(blank=True, max_length=200, verbose_name='表示用注記')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('feeding_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='feeding.feedinggroup', verbose_name='食品群')),
            ],
            options={
                'verbose_name': '月齢別標準量',
                'verbose_name_plural': '月齢別標準量',
                'ordering': ['min_age_months', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('min_age_months', 'max_age_months', 'feeding_group'), name='unique_guideline_per_age_and_group')],
            },
        ),
    ]
