# Generated by Django 5.2.16 on 2026-08-02 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0005_feedinggroup_food_feeding_group_feedingguideline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='finished_amount_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='調理後に完成した料理全体の重量をgで入力する。', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='完成量'),
        ),
        migrations.AddField(
            model_name='dish',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='作り方'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='amount_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='料理全体に使用した材料の重量をgで入力する。', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='使用量'),
        ),
        migrations.AddField(
            model_name='mealitemingredient',
            name='amount_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='実際に食べた材料量'),
        ),
    ]
