# Generated by Django 5.2.16 on 2026-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0006_dish_finished_amount_g_dish_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='reaction',
            field=models.CharField(blank=True, choices=[('love', '大喜び'), ('happy', '嬉'), ('normal', '普'), ('unsure', '微妙')], default='', max_length=10, verbose_name='反応'),
        ),
    ]
