# Generated by Django 5.2.16 on 2026-08-03 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0007_alter_mealitem_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', '保護者'), ('family', '家族'), ('viewer', '閲覧のみ')], default='parent', max_length=20, verbose_name='役割')),
                ('can_edit', models.BooleanField(default=True, verbose_name='編集できる')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='feeding.baby', verbose_name='赤ちゃん')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '赤ちゃんの利用者',
                'verbose_name_plural': '赤ちゃんの利用者',
                'ordering': ['baby', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='baby',
            name='caregivers',
            field=models.ManyToManyField(blank=True, related_name='feeding_babies', through='feeding.BabyMembership', to=settings.AUTH_USER_MODEL, verbose_name='管理ユーザー'),
        ),
        migrations.AddConstraint(
            model_name='babymembership',
            constraint=models.UniqueConstraint(fields=('baby', 'user'), name='unique_user_per_baby'),
        ),
    ]
