# Generated by Django 5.2.16 on 2026-08-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0008_babymembership_baby_caregivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babymembership',
            name='role',
        ),
    ]
