# Generated by Django 5.2.16 on 2026-08-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0009_remove_babymembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名前')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '薬・サプリ',
                'verbose_name_plural': '薬・サプリ',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplementIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('taken', models.BooleanField(default=False, verbose_name='飲んだ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_intakes', to='feeding.baby', verbose_name='子ども')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='feeding.supplement', verbose_name='薬・サプリ')),
            ],
            options={
                'verbose_name': '薬・サプリ摂取記録',
                'verbose_name_plural': '薬・サプリ摂取記録',
                'ordering': ['-date', 'supplement__display_order', 'supplement__name'],
                'constraints': [models.UniqueConstraint(fields=('baby', 'supplement', 'date'), name='unique_supplement_intake_per_baby_and_day')],
            },
        ),
    ]
