# Generated by Django 5.2.16 on 2026-08-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0010_supplement_supplementintake'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothbrushingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('meal_number', models.PositiveSmallIntegerField(choices=[(1, '1食目'), (2, '2食目'), (3, '3食目')], verbose_name='食事番号')),
                ('brushed', models.BooleanField(default=False, verbose_name='歯磨き済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toothbrushing_records', to='feeding.baby', verbose_name='子ども')),
            ],
            options={
                'verbose_name': '歯磨き記録',
                'verbose_name_plural': '歯磨き記録',
                'ordering': ['-date', 'meal_number'],
                'constraints': [models.UniqueConstraint(fields=('baby', 'date', 'meal_number'), name='unique_toothbrushing_record_per_baby_date_and_meal')],
            },
        ),
    ]
