# Generated by Django 5.2.16 on 2026-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0011_toothbrushingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='commercial_brand',
            field=models.CharField(blank=True, choices=[('hipp', 'HiPP'), ('holle', 'Holle')], max_length=20, verbose_name='メーカー'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient_data_note',
            field=models.CharField(blank=True, help_text='例：主要材料のみ割合が明記されている', max_length=255, verbose_name='材料データの注記'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient_data_verified',
            field=models.BooleanField(default=False, help_text='公式の商品ページまたは商品ラベルで、登録材料の割合を確認した場合に有効にする。', verbose_name='材料割合確認済み'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_commercial_product',
            field=models.BooleanField(default=False, verbose_name='市販品'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recommended_from_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='例：5か月からなら5', null=True, verbose_name='対象月齢'),
        ),
        migrations.AddField(
            model_name='dish',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='公式商品ページ'),
        ),
    ]
