# Generated by Django 5.2.16 on 2026-08-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0012_dish_commercial_brand_dish_ingredient_data_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='メーカー名')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '市販品メーカー',
                'verbose_name_plural': '市販品メーカー',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='dish',
            name='commercial_brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='旧メーカーコード'),
        ),
        migrations.AddField(
            model_name='dish',
            name='commercial_brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='feeding.commercialbrand', verbose_name='メーカー'),
        ),
    ]
