# Generated by Django 5.2.16 on 2026-09-03 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('block_breaker', 'ブロック崩し'), ('tap_star', 'スタータップ')], max_length=30)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'game', 'level'), name='unique_game_best_score')],
            },
        ),
    ]
