# Generated by Django 5.2.16 on 2026-09-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('block_breaker', 'ブロック崩し'), ('tap_star', 'スタータップ'), ('maze_chase', 'パッックマン')], max_length=30),
        ),
    ]
