# Generated by Django 5.2.16 on 2026-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamescore_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('block_breaker', 'ブロック崩し'), ('tap_star', 'スタータップ'), ('maze_chase', 'パッックマン'), ('maaario', 'マアアアリオ')], max_length=30),
        ),
    ]
