# Generated by Django 5.2.16 on 2026-10-04 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='confirmed_start_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='scheduling_mode',
            field=models.CharField(choices=[('date_only', '日付だけで決める'), ('time_options', '時間帯から選ぶ'), ('start_times', '開始時刻から選ぶ'), ('free_input', '空き時間を入力してもらう')], default='date_only', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='response_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdateresponse',
            name='event_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_input_responses', to='event_scheduler.eventdate'),
        ),
        migrations.AlterField(
            model_name='eventdateresponse',
            name='response_type',
            field=models.CharField(choices=[('unavailable', '参加できない'), ('all_day', '終日OK'), ('partial', '時間を指定')], max_length=20),
        ),
        migrations.CreateModel(
            name='EventStartTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_time_options', to='event_scheduler.eventdate')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventStartTimeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', '参加できる'), ('maybe', '未定'), ('no', '参加できない')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='event_scheduler.eventstarttimeoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_start_time_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='event_scheduler.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventTimeOptionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', '参加できる'), ('maybe', '未定'), ('no', '参加できない')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_option_votes', to='event_scheduler.eventdate')),
                ('time_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='event_scheduler.eventtimeoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_time_option_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDateVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', '参加できる'), ('maybe', '未定'), ('no', '参加できない')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_votes', to='event_scheduler.eventdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_date_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_date', 'user'), name='unique_event_date_vote')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventstarttimeoption',
            constraint=models.UniqueConstraint(fields=('event_date', 'start_time'), name='unique_event_start_time_option'),
        ),
        migrations.AddConstraint(
            model_name='eventstarttimevote',
            constraint=models.UniqueConstraint(fields=('start_time_option', 'user'), name='unique_event_start_time_vote'),
        ),
        migrations.AddConstraint(
            model_name='eventtimeoptionvote',
            constraint=models.UniqueConstraint(fields=('event_date', 'time_option', 'user'), name='unique_event_time_option_vote'),
        ),
    ]
