# Generated by Django 5.2.16 on 2026-10-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0002_remove_event_confirmed_start_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_mode',
            field=models.CharField(choices=[('none', '指定しない'), ('fixed', '作成者が決める'), ('vote', 'みんなで決める')], default='fixed', max_length=20),
        ),
        migrations.CreateModel(
            name='EventDurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_options', to='event_scheduler.event')),
            ],
            options={
                'ordering': ['order', 'minutes'],
            },
        ),
        migrations.CreateModel(
            name='EventDurationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='event_scheduler.eventdurationoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_duration_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventdurationoption',
            constraint=models.UniqueConstraint(fields=('event', 'minutes'), name='unique_event_duration_option'),
        ),
        migrations.AddConstraint(
            model_name='eventdurationvote',
            constraint=models.UniqueConstraint(fields=('duration_option', 'user'), name='unique_event_duration_vote'),
        ),
    ]
