# Generated by Django 5.2.16 on 2026-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0004_eventadmininvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
