# Generated by Django 5.2.16 on 2026-10-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0005_event_archived_at_event_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_participant_duration_addition',
            field=models.BooleanField(default=False),
        ),
    ]
