# Generated by Django 5.2.16 on 2026-10-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0006_event_allow_participant_duration_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_participant_time_option_addition',
            field=models.BooleanField(default=False),
        ),
    ]
