# Generated by Django 5.2.16 on 2026-10-09 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def populate_share_tokens(apps, schema_editor):

    Event = apps.get_model(
        "event_scheduler",
        "Event",
    )

    database_alias = schema_editor.connection.alias

    events = (
        Event.objects.using(database_alias)
        .filter(share_token__isnull=True)
    )

    for event in events.iterator():

        event.share_token = uuid.uuid4()

        event.save(
            update_fields=["share_token"]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0007_event_allow_participant_time_option_addition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='share_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventdateresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_date_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventdatevote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_date_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventdurationvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_duration_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventstarttimevote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_start_time_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventtimeoptionvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_time_option_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventGuestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('edit_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_participants', to='event_scheduler.event')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='eventdateresponse',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_responses', to='event_scheduler.eventguestparticipant'),
        ),
        migrations.AddField(
            model_name='eventdatevote',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_votes', to='event_scheduler.eventguestparticipant'),
        ),
        migrations.AddField(
            model_name='eventdurationvote',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duration_votes', to='event_scheduler.eventguestparticipant'),
        ),
        migrations.AddField(
            model_name='eventstarttimevote',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_time_votes', to='event_scheduler.eventguestparticipant'),
        ),
        migrations.AddField(
            model_name='eventtimeoptionvote',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_option_votes', to='event_scheduler.eventguestparticipant'),
        ),
        migrations.AddConstraint(
            model_name='eventdateresponse',
            constraint=models.UniqueConstraint(fields=('event_date', 'guest'), name='unique_guest_date_response'),
        ),
        migrations.AddConstraint(
            model_name='eventdateresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='event_date_response_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='eventdatevote',
            constraint=models.UniqueConstraint(fields=('event_date', 'guest'), name='unique_guest_event_date_vote'),
        ),
        migrations.AddConstraint(
            model_name='eventdatevote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='event_date_vote_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='eventdurationvote',
            constraint=models.UniqueConstraint(fields=('duration_option', 'guest'), name='unique_guest_duration_vote'),
        ),
        migrations.AddConstraint(
            model_name='eventdurationvote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='event_duration_vote_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='eventstarttimevote',
            constraint=models.UniqueConstraint(fields=('start_time_option', 'guest'), name='unique_guest_start_time_vote'),
        ),
        migrations.AddConstraint(
            model_name='eventstarttimevote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='event_start_time_vote_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='eventtimeoptionvote',
            constraint=models.UniqueConstraint(fields=('event_date', 'time_option', 'guest'), name='unique_guest_time_option_vote'),
        ),
        migrations.AddConstraint(
            model_name='eventtimeoptionvote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='event_time_vote_one_owner'),
        ),
        migrations.RunPython(
            populate_share_tokens,
            migrations.RunPython.noop,
        ),
    ]
