# Generated by Django 5.2.16 on 2026-10-09 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0008_event_share_token_alter_eventdateresponse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
