"""HiPP / Holle commercial baby-food catalogue snapshot.

Estimated ingredient percentages are AI estimates for in-app approximate tracking.
They are not manufacturer-confirmed nutrition data.
"""

COMMERCIAL_PRODUCTS = [
{'brand': 'hipp',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis mit Kartoffeln',
  'japanese_name': 'かぼちゃとじゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/gemuese/hipp-kuerbis-mit-kartoffeln-ch4145/',
  'ratio_source': 'official_partial',
  'ingredients': [('かぼちゃ', '60', 'official'), ('じゃがいも', '25', 'official')]},
{'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Kürbis mit Kartoffeln und Bio-Rind',
  'japanese_name': 'かぼちゃ・じゃがいも・オーガニック牛肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/hipp-kuerbis-mit-kartoffeln-und-bio-rind-190g-ch6270-01/',
  'ratio_source': 'official_partial',
  'ingredients': [('かぼちゃ', '30', 'official'),
                  ('じゃがいも', '26', 'official'),
                  ('牛肉', '8', 'official'),
                  ('米', '4', 'estimated')]},
{'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Couscous-Gemüse-Pfanne',
  'japanese_name': 'クスクスと野菜の煮込み',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/hipp-couscous-gemuese-pfanne-vegetarisch-190g-6218-02/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '24', 'estimated'),
                  ('トマト', '16', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('クスクス', '10', 'estimated'),
                  ('ひよこ豆', '6', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
{'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Buntes Gemüse mit Linsen und Reis',
  'japanese_name': '彩り野菜・レンズ豆・ごはん',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '22', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('レンズ豆', '8', 'estimated'),
                  ('米', '7', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Bio-Schinkennudeln mit Tomaten & Karotten',
  'japanese_name': 'オーガニックハムパスタ・トマトとにんじん',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'official_partial',
  'ingredients': [('トマト', '33', 'official'),
                  ('にんじん', '30', 'official'),
                  ('ハム', '8.6', 'official'),
                  ('パスタ', '6', 'official'),
                  ('玉ねぎ', '3', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Birne Pflaume mit Vollkorn',
  'japanese_name': '洋なし・プルーン・全粒穀物',
  'finished_amount_g': '90',
  'source_url': 'https://www.hipp.ch/beikost/produkte/fruechte-desserts/frucht-getreide/',
  'ratio_source': 'estimated',
  'ingredients': [('洋なし', '58', 'estimated'),
                  ('プルーン', '20', 'estimated'),
                  ('全粒穀物', '8', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Tomatensuppe mit Hühnchen',
  'japanese_name': '鶏肉入りトマトスープ',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/suppen/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '38', 'estimated'),
                  ('じゃがいも', '18', 'estimated'),
                  ('にんじん', '12', 'estimated'),
                  ('鶏肉', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated'),
                  ('米', '3', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Rote Beete Suppe mit Rind',
  'japanese_name': '牛肉入りビーツスープ',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/suppen/',
  'ratio_source': 'estimated',
  'ingredients': [('ビーツ', '32', 'estimated'),
                  ('じゃがいも', '20', 'estimated'),
                  ('にんじん', '12', 'estimated'),
                  ('牛肉', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 10,
  'recommended_from_month': 9,
  'german_name': 'BIO Früchte-Müesli',
  'japanese_name': 'オーガニックフルーツミューズリー',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/fruechte-desserts/fruechte-mueesli-porridge/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '42', 'estimated'),
                  ('バナナ', '20', 'estimated'),
                  ('洋なし', '15', 'estimated'),
                  ('オートミール', '8', 'estimated'),
                  ('全粒小麦', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 12,
  'recommended_from_month': 11,
  'german_name': 'Pasta Bambini Rigatoni Napoli',
  'japanese_name': '幼児向けリガトーニ・ナポリ風',
  'finished_amount_g': '250',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '34', 'estimated'),
                  ('パスタ', '24', 'estimated'),
                  ('にんじん', '10', 'estimated'),
                  ('ズッキーニ', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Karotten',
  'japanese_name': 'にんじん',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/karotten/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '80', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Pastinakenpüree',
  'japanese_name': 'パースニップピューレ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/pastinakenpueree/',
  'ratio_source': 'estimated',
  'ingredients': [('パースニップ', '80', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Karotten mit Kartoffeln',
  'japanese_name': 'にんじんとじゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/karotten-mit-kartoffeln/',
  'ratio_source': 'official',
  'ingredients': [('にんじん', '50', 'official'), ('じゃがいも', '27', 'official')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis mit Reis',
  'japanese_name': 'かぼちゃとお米',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kuerbis-mit-reis/',
  'ratio_source': 'estimated',
  'ingredients': [('かぼちゃ', '55', 'estimated'), ('米', '8', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis mit Huhn',
  'japanese_name': 'かぼちゃと鶏肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kuerbis-mit-huhn/',
  'ratio_source': 'official_partial',
  'ingredients': [('かぼちゃ', '44', 'official'), ('鶏肉', '8', 'official'), ('米', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis, Zucchini & Kartoffel',
  'japanese_name': 'かぼちゃ・ズッキーニ・じゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kuerbis-zucchini-kartoffel/',
  'ratio_source': 'estimated',
  'ingredients': [('かぼちゃ', '38', 'estimated'),
                  ('ズッキーニ', '24', 'estimated'),
                  ('じゃがいも', '18', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Gemüseallerlei',
  'japanese_name': '彩り野菜',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/gemueseallerlei/',
  'ratio_source': 'official',
  'ingredients': [('にんじん', '45', 'official'),
                  ('じゃがいも', '16', 'official'),
                  ('長ねぎ', '8', 'official'),
                  ('ほうれん草', '4', 'official'),
                  ('パースニップ', '4', 'official')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Spinat mit Kartoffeln',
  'japanese_name': 'ほうれん草とじゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/spinat-mit-kartoffeln/',
  'ratio_source': 'official_partial',
  'ingredients': [('ほうれん草', '23', 'official'), ('じゃがいも', '15', 'official')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Kartoffel, Erbse & Zucchini',
  'japanese_name': 'じゃがいも・グリーンピース・ズッキーニ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kartoffel-erbse-zucchini/',
  'ratio_source': 'estimated',
  'ingredients': [('じゃがいも', '35', 'estimated'),
                  ('グリーンピース', '22', 'estimated'),
                  ('ズッキーニ', '20', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Karotte, Kartoffel & Rind',
  'japanese_name': 'にんじん・じゃがいも・牛肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/karotte-kartoffel-rind/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '38', 'estimated'),
                  ('じゃがいも', '27', 'estimated'),
                  ('牛肉', '8', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Linsengemüse mit Kalb',
  'japanese_name': 'レンズ豆入り野菜と仔牛肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/linsengemuese-mit-kalb/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '25', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('レンズ豆', '10', 'estimated'),
                  ('仔牛肉', '8', 'estimated'),
                  ('じゃがいも', '8', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Gemüserisotto',
  'japanese_name': '野菜リゾット',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/gemueserisotto/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '22', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('米', '10', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Couscous',
  'japanese_name': 'クスクス',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/couscous/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '25', 'estimated'),
                  ('トマト', '18', 'estimated'),
                  ('ズッキーニ', '15', 'estimated'),
                  ('クスクス', '10', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Veggie Curry',
  'japanese_name': '野菜カレー',
  'finished_amount_g': '220',
  'source_url': 'https://www.holle.ch/ch/produkt/veggie-curry/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '20', 'estimated'),
                  ('かぼちゃ', '18', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('ひよこ豆', '10', 'estimated'),
                  ('米', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Spaghetti alla Bolognese',
  'japanese_name': 'スパゲッティ・ボロネーゼ',
  'finished_amount_g': '220',
  'source_url': 'https://www.holle.ch/ch/produkt/spaghetti-alla-bolognese/',
  'ratio_source': 'official_partial',
  'ingredients': [('トマト', '18.7', 'official'),
                  ('にんじん', '16', 'official'),
                  ('全粒スペルトパスタ', '11.4', 'official'),
                  ('牛肉', '8', 'official'),
                  ('長ねぎ', '2', 'official'),
                  ('米', '3', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel pur',
  'japanese_name': 'りんごピューレ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-pur/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '100', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Birne pur',
  'japanese_name': '洋なしピューレ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/birne-pur/',
  'ratio_source': 'estimated',
  'ingredients': [('洋なし', '100', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel & Birne',
  'japanese_name': 'りんごと洋なし',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-birne/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '70', 'estimated'), ('洋なし', '30', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel & Pflaume',
  'japanese_name': 'りんごとプルーン',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-pflaume/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '75', 'estimated'), ('プルーン', '25', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel & Pfirsich',
  'japanese_name': 'りんごと桃',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-pfirsich/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '70', 'estimated'), ('桃', '30', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Apfel & Banane mit Aprikose',
  'japanese_name': 'りんご・バナナ・あんず',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-banane-mit-aprikose/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '50', 'estimated'),
                  ('バナナ', '30', 'estimated'),
                  ('あんず', '20', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Apfel & Birne mit Hafer',
  'japanese_name': 'りんご・洋なし・オート麦',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-birne-mit-hafer/',
  'ratio_source': 'official',
  'ingredients': [('りんご', '45', 'official'),
                  ('洋なし', '28', 'official'),
                  ('オートミール', '4.3', 'official')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Apfel & Banane mit Dinkel',
  'japanese_name': 'りんご・バナナ・スペルト小麦',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-banane-mit-dinkel/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '50', 'estimated'),
                  ('バナナ', '30', 'estimated'),
                  ('スペルト小麦', '5', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Bio Apfel & Heidelbeeren',
  'japanese_name': 'オーガニックりんごとブルーベリー',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/bio-apfel-heidelbeeren/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '80', 'estimated'), ('ブルーベリー', '20', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Waldbeeren in Apfel',
  'japanese_name': 'りんごと森のベリー',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/waldbeeren-in-apfel/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '75', 'estimated'),
                  ('ブルーベリー', '8', 'estimated'),
                  ('ラズベリー', '7', 'estimated'),
                  ('いちご', '5', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Birchermüesli',
  'japanese_name': 'ビルヒャーミューズリー',
  'finished_amount_g': '220',
  'source_url': 'https://www.holle.ch/ch/produkt/birchermueesli/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '45', 'estimated'),
                  ('バナナ', '18', 'estimated'),
                  ('オートミール', '8', 'estimated'),
                  ('全粒小麦', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Hühnchenfleisch',
  'japanese_name': '鶏肉',
  'finished_amount_g': '125',
  'source_url': 'https://www.holle.ch/ch/produkt/huehnchenfleisch/',
  'ratio_source': 'estimated',
  'ingredients': [('鶏肉', '40', 'estimated'), ('米', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Rindfleisch',
  'japanese_name': '牛肉',
  'finished_amount_g': '125',
  'source_url': 'https://www.holle.ch/ch/produkt/rindfleisch/',
  'ratio_source': 'estimated',
  'ingredients': [('牛肉', '40', 'estimated'), ('米', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Spaghetti mit Linsen-Bolognese',
  'japanese_name': 'レンズ豆のボロネーゼ風スパゲッティ',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '28', 'estimated'),
                  ('にんじん', '18', 'estimated'),
                  ('レンズ豆', '10', 'estimated'),
                  ('パスタ', '9', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Spaghetti mit Erbsen-Bolognese',
  'japanese_name': 'グリーンピースのボロネーゼ風スパゲッティ',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '26', 'estimated'),
                  ('にんじん', '18', 'estimated'),
                  ('グリーンピース', '12', 'estimated'),
                  ('パスタ', '9', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Makkaroni mit Erbsen-Gemüse',
  'japanese_name': 'マカロニとグリーンピース野菜',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('パスタ', '16', 'estimated'),
                  ('グリーンピース', '18', 'estimated'),
                  ('にんじん', '16', 'estimated'),
                  ('トマト', '12', 'estimated'),
                  ('ズッキーニ', '10', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Cremiger Gemüse-Reis mit Kichererbsen',
  'japanese_name': 'ひよこ豆入りクリーミー野菜ごはん',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('米', '12', 'estimated'),
                  ('ひよこ豆', '9', 'estimated'),
                  ('にんじん', '18', 'estimated'),
                  ('ズッキーニ', '15', 'estimated'),
                  ('トマト', '10', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Couscous mit Gemüse und Bio-Hühnchen',
  'japanese_name': '野菜とオーガニック鶏肉のクスクス',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('クスクス', '11', 'estimated'),
                  ('鶏肉', '8', 'estimated'),
                  ('にんじん', '18', 'estimated'),
                  ('トマト', '14', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Kartoffel-Gemüse mit Bio-Rind',
  'japanese_name': 'じゃがいもと野菜・オーガニック牛肉',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('じゃがいも', '28', 'estimated'),
                  ('にんじん', '20', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('牛肉', '8', 'estimated'),
                  ('玉ねぎ', '3', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Penne mit Tomaten und Zucchetti',
  'japanese_name': 'トマトとズッキーニのペンネ',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('パスタ', '18', 'estimated'),
                  ('トマト', '30', 'estimated'),
                  ('ズッキーニ', '18', 'estimated'),
                  ('にんじん', '10', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Gemüsereis mit Bio-Poulet',
  'japanese_name': '野菜ごはんとオーガニック鶏肉',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('米', '12', 'estimated'),
                  ('鶏肉', '8', 'estimated'),
                  ('にんじん', '20', 'estimated'),
                  ('トマト', '14', 'estimated'),
                  ('ズッキーニ', '12', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Bio-Schinkennudeln mit Gemüse',
  'japanese_name': 'オーガニックハムパスタと野菜',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('パスタ', '16', 'estimated'),
                  ('ハム', '8', 'estimated'),
                  ('にんじん', '18', 'estimated'),
                  ('トマト', '14', 'estimated'),
                  ('ズッキーニ', '10', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Gemüse und Reis mit Bio-Kalb',
  'japanese_name': '野菜とごはん・オーガニック仔牛肉',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('米', '11', 'estimated'),
                  ('仔牛肉', '8', 'estimated'),
                  ('にんじん', '20', 'estimated'),
                  ('トマト', '14', 'estimated'),
                  ('ズッキーニ', '10', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Spaghetti Bolognese',
  'japanese_name': 'スパゲッティ・ボロネーゼ',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '28', 'estimated'),
                  ('パスタ', '16', 'estimated'),
                  ('牛肉', '8', 'estimated'),
                  ('にんじん', '14', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Tomatennudeln mit Bio-Kalb',
  'japanese_name': 'トマトパスタとオーガニック仔牛肉',
  'finished_amount_g': '220',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '30', 'estimated'),
                  ('パスタ', '17', 'estimated'),
                  ('仔牛肉', '8', 'estimated'),
                  ('にんじん', '12', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 12,
  'recommended_from_month': 11,
  'german_name': 'Vegetarisches Menü Gemüse-Risotto',
  'japanese_name': 'ベジタリアン野菜リゾット',
  'finished_amount_g': '250',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('米', '14', 'estimated'),
                  ('にんじん', '18', 'estimated'),
                  ('トマト', '14', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('グリーンピース', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
# ------------------------------
# HiPP パウチ
# ------------------------------
{
    "brand": "hipp",
    "display_month": 5,
    "recommended_from_month": 4,
    "german_name": "Baby-Quetschbeutel Apfel-Banane und Babykeks",
    "japanese_name": "りんご・バナナ・ベビービスケット",
    "finished_amount_g": "90",
    "source_url": "https://www.hipp.ch/beikost/produkte/fruechte-desserts/frucht-getreide/hipp-baby-quetschbeutel-apfel-banane-und-babykeks-ch8579-01/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "55", "estimated"),
        ("バナナ", "30", "estimated"),
        ("ビスケット", "8", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 5,
    "recommended_from_month": 4,
    "german_name": "Frucht & Getreide Mango Banane Griess",
    "japanese_name": "マンゴー・バナナ・セモリナ",
    "finished_amount_g": "90",
    "source_url": "https://www.hipp.ch/beikost/produkte/fruechte-desserts/frucht-getreide/hipp-frucht-getreide-mango-banane-griess-4x90g-da47017/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "40", "estimated"),
        ("バナナ", "28", "estimated"),
        ("マンゴー", "18", "estimated"),
        ("小麦", "6", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 5,
    "recommended_from_month": 4,
    "german_name": "Frucht & Getreide Mango Pfirsich in Banane mit Hafer",
    "japanese_name": "マンゴー・桃・バナナ・オート麦",
    "finished_amount_g": "90",
    "source_url": "https://www.hipp.ch/beikost/produkte/fruechte-desserts/frucht-getreide/",
    "ratio_source": "estimated",
    "ingredients": [
        ("バナナ", "40", "estimated"),
        ("マンゴー", "22", "estimated"),
        ("桃", "20", "estimated"),
        ("オートミール", "6", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Apfel Birne Banane",
    "japanese_name": "りんご・洋なし・バナナ",
    "finished_amount_g": "100",
    "source_url": "https://www.hipp.ch/kinder/produkte/quetschbeutel/100-fruechte/hipp-apfel-birne-banane-100g-ch8520-01/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "45", "estimated"),
        ("バナナ", "30", "estimated"),
        ("洋なし", "25", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Erdbeere Banane in Apfel",
    "japanese_name": "りんご・いちご・バナナ",
    "finished_amount_g": "100",
    "source_url": "https://www.hipp.ch/kinder/produkte/quetschbeutel/100-fruechte/hipp-erdbeere-banane-in-apfel-4x100g/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "60", "estimated"),
        ("バナナ", "25", "estimated"),
        ("いちご", "15", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Waldbeeren in Apfel Pfirsich",
    "japanese_name": "りんご・桃・森のベリー",
    "finished_amount_g": "100",
    "source_url": "https://www.hipp.ch/kinder/produkte/quetschbeutel/100-fruechte/hipp-waldbeeren-in-apfel-pfirsich-4x100g-ch8537-01s/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "55", "estimated"),
        ("桃", "20", "estimated"),
        ("ブルーベリー", "10", "estimated"),
        ("ラズベリー", "8", "estimated"),
        ("いちご", "7", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Mango Maracuja in Birne Apfel",
    "japanese_name": "洋なし・りんご・マンゴー・パッションフルーツ",
    "finished_amount_g": "100",
    "source_url": "https://www.hipp.ch/kinder/produkte/quetschbeutel/100-fruechte/hipp-mango-maracuja-in-birne-apfel-100g-ch8570-01/",
    "ratio_source": "estimated",
    "ingredients": [
        ("洋なし", "35", "estimated"),
        ("りんご", "30", "estimated"),
        ("マンゴー", "25", "estimated"),
        ("パッションフルーツ", "10", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Mirabelle in Apfel Pfirsich",
    "japanese_name": "りんご・桃・ミラベル",
    "finished_amount_g": "100",
    "source_url": "https://www.hipp.ch/kinder/produkte/quetschbeutel/100-fruechte/hipp-mirabelle-in-apfel-pfirsich-100g-ch42506/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "50", "estimated"),
        ("桃", "30", "estimated"),
        ("プルーン", "20", "estimated"),
    ],
},
{
    "brand": "hipp",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Drachenfrucht Johannisbeere in Apfel Birne",
    "japanese_name": "りんご・洋なし・ドラゴンフルーツ・カシス",
    "finished_amount_g": "100",
    "source_url": "https://www.hipp.ch/kinder/produkte/quetschbeutel/100-fruechte/hipp-drachenfrucht-johannisbeere-in-apfel-birne-100g-ch42507/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "45", "estimated"),
        ("洋なし", "30", "estimated"),
        ("ドラゴンフルーツ", "15", "estimated"),
        ("カシス", "10", "estimated"),
    ],
},

# ------------------------------
# Holle パウチ
# ------------------------------
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Banana Lama – Banane, Apfel, Mango & Aprikose",
    "japanese_name": "バナナ・りんご・マンゴー・あんず",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/banana-lama-banane-apfel-mango-aprikose/",
    "ratio_source": "official",
    "ingredients": [
        ("バナナ", "46", "official"),
        ("りんご", "33", "official"),
        ("マンゴー", "14", "official"),
        ("あんず", "6.9", "official"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Panda Peach – Pfirsich, Aprikose & Banane mit Dinkel",
    "japanese_name": "桃・あんず・バナナ・スペルト小麦",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/panda-peach-pfirsich-aprikose-banane-mit-dinkel/",
    "ratio_source": "official",
    "ingredients": [
        ("桃", "40", "official"),
        ("バナナ", "33", "official"),
        ("あんず", "25", "official"),
        ("スペルト小麦", "2", "official"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Zebra Beet – Apfel & Banane mit Rote Bete",
    "japanese_name": "りんご・バナナ・ビーツ",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/zebra-beet-apfel-banane-mit-rote-bete/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "50", "estimated"),
        ("バナナ", "35", "estimated"),
        ("ビーツ", "15", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Apple Ant – Apfel & Banane mit Birne",
    "japanese_name": "りんご・バナナ・洋なし",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/apple-ant-apfel-banane-mit-birne/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "45", "estimated"),
        ("バナナ", "30", "estimated"),
        ("洋なし", "25", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Red Bee – Apfel mit Erdbeere",
    "japanese_name": "りんごといちご",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/red-bee-apfel-mit-erdbeere/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "80", "estimated"),
        ("いちご", "20", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Tropic Tiger – Apfel mit Mango & Maracuja",
    "japanese_name": "りんご・マンゴー・パッションフルーツ",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/tropic-tiger-apfel-mit-mango-maracuja/",
    "ratio_source": "estimated",
    "ingredients": [
        ("りんご", "60", "estimated"),
        ("マンゴー", "30", "estimated"),
        ("パッションフルーツ", "10", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Kiwi Koala – Birne & Banane mit Kiwi",
    "japanese_name": "洋なし・バナナ・キウイ",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/kiwi-koala-birne-banane-mit-kiwi/",
    "ratio_source": "estimated",
    "ingredients": [
        ("洋なし", "45", "estimated"),
        ("バナナ", "35", "estimated"),
        ("キウイ", "20", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Carrot Cat – Karotte, Mango, Banane & Birne",
    "japanese_name": "にんじん・マンゴー・バナナ・洋なし",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/carrot-cat-karotte-mango-banane-birne/",
    "ratio_source": "estimated",
    "ingredients": [
        ("にんじん", "30", "estimated"),
        ("マンゴー", "25", "estimated"),
        ("バナナ", "25", "estimated"),
        ("洋なし", "20", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Power Parrot – Birne & Apfel mit Spinat",
    "japanese_name": "洋なし・りんご・ほうれん草",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/power-parrot-birne-apfel-mit-spinat/",
    "ratio_source": "estimated",
    "ingredients": [
        ("洋なし", "45", "estimated"),
        ("りんご", "40", "estimated"),
        ("ほうれん草", "15", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Veggie Bunny – Karotte & Süsskartoffel mit Erbsen",
    "japanese_name": "にんじん・さつまいも・グリーンピース",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/veggie-bunny-karotte-suesskartoffel-mit-erbsen/",
    "ratio_source": "official",
    "ingredients": [
        ("にんじん", "68", "official"),
        ("さつまいも", "20", "official"),
        ("グリーンピース", "8.5", "official"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Lazy Sweetato – Süsskartoffel, Pflaume, Kürbis, Erdbeere und Hafer",
    "japanese_name": "さつまいも・プルーン・かぼちゃ・いちご・オート麦",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/lazy-sweetato-suesskartoffel-pflaume-kuerbis-erdbeere-und-hafer/",
    "ratio_source": "official",
    "ingredients": [
        ("さつまいも", "31.5", "official"),
        ("プルーン", "28", "official"),
        ("かぼちゃ", "28", "official"),
        ("いちご", "10", "official"),
        ("オートミール", "2", "official"),
    ],
},
{
    "brand": "holle",
    "display_month": 6,
    "recommended_from_month": 5,
    "german_name": "Pelican Peach – Pfirsich, Erdbeere, Apfel und Hafer",
    "japanese_name": "桃・いちご・りんご・オート麦",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/pelican-peach-pfirsich-erdbeere-apfel-und-hafer/",
    "ratio_source": "estimated",
    "ingredients": [
        ("桃", "40", "estimated"),
        ("りんご", "30", "estimated"),
        ("いちご", "20", "estimated"),
        ("オートミール", "5", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 8,
    "recommended_from_month": 7,
    "german_name": "Fruity Fox – Apfel, Banane & Beeren mit Joghurt",
    "japanese_name": "りんご・バナナ・ベリー・ヨーグルト",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/fruity-fox-apfel-banane-beeren-mit-joghurt/",
    "ratio_source": "official",
    "ingredients": [
        ("ヨーグルト", "40", "official"),
        ("りんご", "24", "official"),
        ("バナナ", "17", "official"),
        ("いちご", "9", "official"),
        ("ブラックベリー", "4", "official"),
        ("カシス", "4", "official"),
    ],
},
{
    "brand": "holle",
    "display_month": 8,
    "recommended_from_month": 7,
    "german_name": "Tasty Turtle – Apfel & Birne mit Joghurt",
    "japanese_name": "りんご・洋なし・ヨーグルト",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/tasty-turtle-apfel-birne-mit-joghurt/",
    "ratio_source": "estimated",
    "ingredients": [
        ("ヨーグルト", "40", "estimated"),
        ("りんご", "35", "estimated"),
        ("洋なし", "25", "estimated"),
    ],
},
{
    "brand": "holle",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Penguin Porridge – Apfel & Beeren mit Hafer & Quinoa",
    "japanese_name": "りんご・ベリー・オート麦・キヌアのポリッジ",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/penguin-porridge-apfel-beeren-mit-hafer-quinoa/",
    "ratio_source": "official",
    "ingredients": [
        ("りんご", "40.5", "official"),
        ("米", "4.2", "official"),
        ("いちご", "10", "official"),
        ("ブルーベリー", "9", "official"),
        ("オートミール", "4", "official"),
        ("キヌア", "1.5", "official"),
    ],
},
{
    "brand": "holle",
    "display_month": 12,
    "recommended_from_month": 11,
    "german_name": "Lion Porridge – Mango & Ananas mit Hafer & Quinoa",
    "japanese_name": "マンゴー・パイナップル・オート麦・キヌアのポリッジ",
    "finished_amount_g": "100",
    "source_url": "https://www.holle.ch/ch/produkt/lion-porridge-mango-ananas-mit-hafer-quinoa/",
    "ratio_source": "official",
    "ingredients": [
        ("りんご", "35.8", "official"),
        ("米", "3.5", "official"),
        ("マンゴー", "19", "official"),
        ("パイナップル", "11", "official"),
        ("オートミール", "4", "official"),
        ("キヌア", "1.2", "official"),
    ]}]