"""HiPP / Holle commercial baby-food catalogue snapshot.

Estimated ingredient percentages are AI estimates for in-app approximate tracking.
They are not manufacturer-confirmed nutrition data.
"""

COMMERCIAL_PRODUCTS = [
{'brand': 'hipp',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis mit Kartoffeln',
  'japanese_name': 'かぼちゃとじゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/gemuese/hipp-kuerbis-mit-kartoffeln-ch4145/',
  'ratio_source': 'official_partial',
  'ingredients': [('かぼちゃ', '60', 'official'),
                  ('じゃがいも', '25', 'official')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Kürbis mit Kartoffeln und Bio-Rind',
  'japanese_name': 'かぼちゃ・じゃがいも・オーガニック牛肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/hipp-kuerbis-mit-kartoffeln-und-bio-rind-190g-ch6270-01/',
  'ratio_source': 'official_partial',
  'ingredients': [('かぼちゃ', '30', 'official'),
                  ('じゃがいも', '26', 'official'),
                  ('牛肉', '8', 'official'),
                  ('米', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Couscous-Gemüse-Pfanne',
  'japanese_name': 'クスクスと野菜の煮込み',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/hipp-couscous-gemuese-pfanne-vegetarisch-190g-6218-02/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '24', 'estimated'),
                  ('トマト', '16', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('クスクス', '10', 'estimated'),
                  ('ひよこ豆', '6', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Buntes Gemüse mit Linsen und Reis',
  'japanese_name': '彩り野菜・レンズ豆・ごはん',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '22', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('レンズ豆', '8', 'estimated'),
                  ('米', '7', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Bio-Schinkennudeln mit Tomaten & Karotten',
  'japanese_name': 'オーガニックハムパスタ・トマトとにんじん',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'official_partial',
  'ingredients': [('トマト', '33', 'official'),
                  ('にんじん', '30', 'official'),
                  ('ハム', '8.6', 'official'),
                  ('パスタ', '6', 'official'),
                  ('玉ねぎ', '3', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Birne Pflaume mit Vollkorn',
  'japanese_name': '洋なし・プルーン・全粒穀物',
  'finished_amount_g': '90',
  'source_url': 'https://www.hipp.ch/beikost/produkte/fruechte-desserts/frucht-getreide/',
  'ratio_source': 'estimated',
  'ingredients': [('洋なし', '58', 'estimated'),
                  ('プルーン', '20', 'estimated'),
                  ('全粒穀物', '8', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Tomatensuppe mit Hühnchen',
  'japanese_name': '鶏肉入りトマトスープ',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/suppen/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '38', 'estimated'),
                  ('じゃがいも', '18', 'estimated'),
                  ('にんじん', '12', 'estimated'),
                  ('鶏肉', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated'),
                  ('米', '3', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Rote Beete Suppe mit Rind',
  'japanese_name': '牛肉入りビーツスープ',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/suppen/',
  'ratio_source': 'estimated',
  'ingredients': [('ビーツ', '32', 'estimated'),
                  ('じゃがいも', '20', 'estimated'),
                  ('にんじん', '12', 'estimated'),
                  ('牛肉', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 10,
  'recommended_from_month': 9,
  'german_name': 'BIO Früchte-Müesli',
  'japanese_name': 'オーガニックフルーツミューズリー',
  'finished_amount_g': '190',
  'source_url': 'https://www.hipp.ch/beikost/produkte/fruechte-desserts/fruechte-mueesli-porridge/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '42', 'estimated'),
                  ('バナナ', '20', 'estimated'),
                  ('洋なし', '15', 'estimated'),
                  ('オートミール', '8', 'estimated'),
                  ('全粒小麦', '4', 'estimated')]},
 {'brand': 'hipp',
  'display_month': 12,
  'recommended_from_month': 11,
  'german_name': 'Pasta Bambini Rigatoni Napoli',
  'japanese_name': '幼児向けリガトーニ・ナポリ風',
  'finished_amount_g': '250',
  'source_url': 'https://www.hipp.ch/beikost/produkte/menues/',
  'ratio_source': 'estimated',
  'ingredients': [('トマト', '34', 'estimated'),
                  ('パスタ', '24', 'estimated'),
                  ('にんじん', '10', 'estimated'),
                  ('ズッキーニ', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Karotten',
  'japanese_name': 'にんじん',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/karotten/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '80', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Pastinakenpüree',
  'japanese_name': 'パースニップピューレ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/pastinakenpueree/',
  'ratio_source': 'estimated',
  'ingredients': [('パースニップ', '80', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Karotten mit Kartoffeln',
  'japanese_name': 'にんじんとじゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/karotten-mit-kartoffeln/',
  'ratio_source': 'official',
  'ingredients': [('にんじん', '50', 'official'), ('じゃがいも', '27', 'official')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis mit Reis',
  'japanese_name': 'かぼちゃとお米',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kuerbis-mit-reis/',
  'ratio_source': 'estimated',
  'ingredients': [('かぼちゃ', '55', 'estimated'), ('米', '8', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis mit Huhn',
  'japanese_name': 'かぼちゃと鶏肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kuerbis-mit-huhn/',
  'ratio_source': 'official_partial',
  'ingredients': [('かぼちゃ', '44', 'official'), ('鶏肉', '8', 'official'), ('米', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Kürbis, Zucchini & Kartoffel',
  'japanese_name': 'かぼちゃ・ズッキーニ・じゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kuerbis-zucchini-kartoffel/',
  'ratio_source': 'estimated',
  'ingredients': [('かぼちゃ', '38', 'estimated'),
                  ('ズッキーニ', '24', 'estimated'),
                  ('じゃがいも', '18', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Gemüseallerlei',
  'japanese_name': '彩り野菜',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/gemueseallerlei/',
  'ratio_source': 'official',
  'ingredients': [('にんじん', '45', 'official'),
                  ('じゃがいも', '16', 'official'),
                  ('長ねぎ', '8', 'official'),
                  ('ほうれん草', '4', 'official'),
                  ('パースニップ', '4', 'official')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Spinat mit Kartoffeln',
  'japanese_name': 'ほうれん草とじゃがいも',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/spinat-mit-kartoffeln/',
  'ratio_source': 'official_partial',
  'ingredients': [('ほうれん草', '23', 'official'), ('じゃがいも', '15', 'official')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Kartoffel, Erbse & Zucchini',
  'japanese_name': 'じゃがいも・グリーンピース・ズッキーニ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/kartoffel-erbse-zucchini/',
  'ratio_source': 'estimated',
  'ingredients': [('じゃがいも', '35', 'estimated'),
                  ('グリーンピース', '22', 'estimated'),
                  ('ズッキーニ', '20', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Karotte, Kartoffel & Rind',
  'japanese_name': 'にんじん・じゃがいも・牛肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/karotte-kartoffel-rind/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '38', 'estimated'),
                  ('じゃがいも', '27', 'estimated'),
                  ('牛肉', '8', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Linsengemüse mit Kalb',
  'japanese_name': 'レンズ豆入り野菜と仔牛肉',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/linsengemuese-mit-kalb/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '25', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('レンズ豆', '10', 'estimated'),
                  ('仔牛肉', '8', 'estimated'),
                  ('じゃがいも', '8', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Gemüserisotto',
  'japanese_name': '野菜リゾット',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/gemueserisotto/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '22', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('ズッキーニ', '12', 'estimated'),
                  ('米', '10', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Couscous',
  'japanese_name': 'クスクス',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/couscous/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '25', 'estimated'),
                  ('トマト', '18', 'estimated'),
                  ('ズッキーニ', '15', 'estimated'),
                  ('クスクス', '10', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Veggie Curry',
  'japanese_name': '野菜カレー',
  'finished_amount_g': '220',
  'source_url': 'https://www.holle.ch/ch/produkt/veggie-curry/',
  'ratio_source': 'estimated',
  'ingredients': [('にんじん', '20', 'estimated'),
                  ('かぼちゃ', '18', 'estimated'),
                  ('トマト', '15', 'estimated'),
                  ('ひよこ豆', '10', 'estimated'),
                  ('米', '8', 'estimated'),
                  ('玉ねぎ', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Spaghetti alla Bolognese',
  'japanese_name': 'スパゲッティ・ボロネーゼ',
  'finished_amount_g': '220',
  'source_url': 'https://www.holle.ch/ch/produkt/spaghetti-alla-bolognese/',
  'ratio_source': 'official_partial',
  'ingredients': [('トマト', '18.7', 'official'),
                  ('にんじん', '16', 'official'),
                  ('全粒スペルトパスタ', '11.4', 'official'),
                  ('牛肉', '8', 'official'),
                  ('長ねぎ', '2', 'official'),
                  ('米', '3', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel pur',
  'japanese_name': 'りんごピューレ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-pur/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '100', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Birne pur',
  'japanese_name': '洋なしピューレ',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/birne-pur/',
  'ratio_source': 'estimated',
  'ingredients': [('洋なし', '100', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel & Birne',
  'japanese_name': 'りんごと洋なし',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-birne/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '70', 'estimated'), ('洋なし', '30', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel & Pflaume',
  'japanese_name': 'りんごとプルーン',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-pflaume/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '75', 'estimated'), ('プルーン', '25', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Apfel & Pfirsich',
  'japanese_name': 'りんごと桃',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-pfirsich/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '70', 'estimated'), ('桃', '30', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Apfel & Banane mit Aprikose',
  'japanese_name': 'りんご・バナナ・あんず',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-banane-mit-aprikose/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '50', 'estimated'),
                  ('バナナ', '30', 'estimated'),
                  ('あんず', '20', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Apfel & Birne mit Hafer',
  'japanese_name': 'りんご・洋なし・オート麦',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-birne-mit-hafer/',
  'ratio_source': 'official',
  'ingredients': [('りんご', '45', 'official'),
                  ('洋なし', '28', 'official'),
                  ('オートミール', '4.3', 'official')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Apfel & Banane mit Dinkel',
  'japanese_name': 'りんご・バナナ・スペルト小麦',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/apfel-banane-mit-dinkel/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '50', 'estimated'),
                  ('バナナ', '30', 'estimated'),
                  ('スペルト小麦', '5', 'estimated')]},
 {'brand': 'holle',
  'display_month': 6,
  'recommended_from_month': 5,
  'german_name': 'Bio Apfel & Heidelbeeren',
  'japanese_name': 'オーガニックりんごとブルーベリー',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/bio-apfel-heidelbeeren/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '80', 'estimated'), ('ブルーベリー', '20', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Waldbeeren in Apfel',
  'japanese_name': 'りんごと森のベリー',
  'finished_amount_g': '190',
  'source_url': 'https://www.holle.ch/ch/produkt/waldbeeren-in-apfel/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '75', 'estimated'),
                  ('ブルーベリー', '8', 'estimated'),
                  ('ラズベリー', '7', 'estimated'),
                  ('いちご', '5', 'estimated')]},
 {'brand': 'holle',
  'display_month': 8,
  'recommended_from_month': 7,
  'german_name': 'Birchermüesli',
  'japanese_name': 'ビルヒャーミューズリー',
  'finished_amount_g': '220',
  'source_url': 'https://www.holle.ch/ch/produkt/birchermueesli/',
  'ratio_source': 'estimated',
  'ingredients': [('りんご', '45', 'estimated'),
                  ('バナナ', '18', 'estimated'),
                  ('オートミール', '8', 'estimated'),
                  ('全粒小麦', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Hühnchenfleisch',
  'japanese_name': '鶏肉',
  'finished_amount_g': '125',
  'source_url': 'https://www.holle.ch/ch/produkt/huehnchenfleisch/',
  'ratio_source': 'estimated',
  'ingredients': [('鶏肉', '40', 'estimated'), ('米', '4', 'estimated')]},
 {'brand': 'holle',
  'display_month': 5,
  'recommended_from_month': 4,
  'german_name': 'Rindfleisch',
  'japanese_name': '牛肉',
  'finished_amount_g': '125',
  'source_url': 'https://www.holle.ch/ch/produkt/rindfleisch/',
  'ratio_source': 'estimated',
  'ingredients': [('牛肉', '40', 'estimated'), ('米', '4', 'estimated')]}]
