# Generated by Django 5.2.16 on 2026-09-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='固定のお知らせ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '掲示板の投稿',
                'verbose_name_plural': '掲示板の投稿',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_comments', to=settings.AUTH_USER_MODEL, verbose_name='コメント投稿者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.boardpost', verbose_name='投稿')),
            ],
            options={
                'verbose_name': '掲示板のコメント',
                'verbose_name_plural': '掲示板のコメント',
                'ordering': ['created_at'],
            },
        ),
    ]
