# Generated by Django 5.2.16 on 2026-10-07 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='audience_type',
            field=models.CharField(choices=[('all', '全ユーザー'), ('include', '指定したユーザーだけ'), ('exclude', '指定したユーザーを除く')], default='all', max_length=20, verbose_name='公開範囲'),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='audience_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_board_posts', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー'),
        ),
    ]
